Excercise.create(name: "Run/Walk 1.5 miles", value: 3)
Excercise.create(name: "Swim 500 meters", value: 3)
Excercise.create(name: "10 pull-ups", value: 1)
Excercise.create(name: "2 minute plank", value: 2)
Excercise.create(name: "60 push-ups", value: 3)
Excercise.create(name: "60 sit-ups", value: 3)
Excercise.create(name: "20 squats", value: 1)
Excercise.create(name: "Row 2000 meters", value: 3)
Excercise.create(name: "10 burpees", value: 2)
Excercise.create(name: "Bike 4 miles", value: 3)
Excercise.create(name: "1 minute brick tread", value: 2)